### ISSUE TITLE
Can't get past OAuth authentication

### ISSUE THREAD

**Issue by Jasius** [vanilevsky/ms-todo-automator#1]
Hey, I've tried your extension and OAuth seems to trigger correctly and tokens get captured, however everything after oAuth flow fail to function. I'm not sure if I've missed something obvious or if there's an issue with the current release, thanks!

<img width="862" alt="image" src="https://user-images.githubusercontent.com/11031051/174483344-e03bb8b7-d6ee-4a63-857d-cf3bb7f08fc6.png">

**Comment by vanilevsky** [comment]
@Jasius Hello! Thanks for the issue. I don't know what concrete version you tried. Can you try with [the first release](https://github.com/vanilevsky/ms-todo-automator/tree/0.1.0) again?

Truly I didn't make a note about how to create right MS App for this, but I hope you know?

**Comment by Jasius** [comment]
I'll give it a shot, thanks. I do know that and I configured what was needed on my own.
